# Example
# kubectl create secret tls konsumo-ssl -n konsumo --cert=/opt/konsumo/ssl/cert.pem  --key=/opt/konsumo/ssl/key.pem
kind: Secret
apiVersion: v1
metadata:
  name: konsumo-ssl
data:
  tls.crt: "..."
  tls.key: "..."
type: kubernetes.io/tls
