apiVersion: batch/v1
kind: Job
metadata:
  name: app-msteams-notif-success-angular
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: msteams-notification-success-angular
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-msteams-notif-failure-angular
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: msteams-notification-failure-angular
      restartPolicy: Never
  backoffLimit: 2