apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: konsumo
bases:
- ../../base
resources:
- configmap.yaml
# - secret.yaml 
patchesJson6902:
- target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: konsumo
  path: route.yaml
- target:
    version: v1
    group: apps
    kind: Deployment
    name: konsumo
  path: deployment.yaml
patchesStrategicMerge:
- merge.yaml
# - postsync-failure-merge.yaml
# - postsync-success-merge.yaml
