---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: konsumo-dev
  name: 'mariadb'
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: container
          image: mariadb:10.11
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: data-volume
      volumes:
        - name: data-volume
          emptyDir:
            sizeLimit: 1Gi              
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP