apiVersion: batch/v1
kind: Job
metadata:
  name: app-msteams-notif-failure-angular
spec:
  template:
    spec:
      containers:
      - name: msteams-notification-failure-angular
        image: fixme/curlimages:latest
        command: 
          - 'curl'
          - '-H'
          - 'Content-Type: application/json'
          - '-d'
          - '{ "text": "Pipeline argo deployment FAILED for konsumo in dev", "@context": "https://schema.org/extensions", "@type": "MessageCard", "themeColor": "0072C6" }'
          - 'https://thelink-TOMSTEAMS'